TARGET_NAMES += HereditaryStratigraphicColumn
TARGET_NAMES += HereditaryStratigraphicColumnBundle
TARGET_NAMES += HereditaryStratum

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/cpp/tests/MaketemplateRunning
