#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMINIMAL_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMINIMAL_HPP_INCLUDE

namespace hstrat {

class StratumRetentionPredicateMinimal {
  // TODO
};


} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMINIMAL_HPP_INCLUDE
