#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEFIXEDRESOLUTION_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEFIXEDRESOLUTION_HPP_INCLUDE

namespace hstrat {

class StratumRetentionPredicateFixedResolution {
  // TODO
};

} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEFIXEDRESOLUTION_HPP_INCLUDE
