#pragma once
#ifndef HSTRAT_HEREDITARYSTRATIGRAPHICCOLUMNBUNDLE_HPP_INCLUDE
#define HSTRAT_HEREDITARYSTRATIGRAPHICCOLUMNBUNDLE_HPP_INCLUDE

namespace hstrat {

class HereditaryStratigraphicColumnBundle {
  // TODO
};

} // namespace hstrat

#endif // #ifndef HSTRAT_HEREDITARYSTRATIGRAPHICCOLUMNBUNDLE_HPP_INCLUDE
