TARGET_NAMES += StratumRetentionPredicateDepthProportionalResolution
TARGET_NAMES += StratumRetentionPredicateFixedResolution
TARGET_NAMES += StratumRetentionPredicateMaximal
TARGET_NAMES += StratumRetentionPredicateMinimal
TARGET_NAMES += StratumRetentionPredicateRecencyProportionalResolution
TARGET_NAMES += StratumRetentionPredicateRecursiveInterspersion
TARGET_NAMES += StratumRetentionPredicateStochastic

TO_ROOT := $(shell git rev-parse --show-cdup)

include $(TO_ROOT)/cpp/tests/MaketemplateRunning
