---
title: "R Notebook"
output: html_notebook
---

```{r setup, echo=TRUE}
library(TreeDist)
library(readr)
library(ape)
library(tidytree)
library(dplyr)
library(ggplot2)
library('Ternary')
library(reticulate)
py_install("alifedata-phyloinformatics-convert", pip=TRUE)
source_python("python_helper.py")
```


```{python}
import alifedata_phyloinformatics_convert as apc
import pandas as pd

```

```{r load_data}

# Load actual phylogenies
sharing <- read_csv("../phylogeny_visualizations/nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv")

ecoea <- read_csv("../phylogeny_visualizations/nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv")

lexicase <- read_csv("../phylogeny_visualizations/nk_lexicaseselection_seed110_pop165_mut.01_snapshot_500.csv")

tournament <- read_csv("../phylogeny_visualizations/nk_tournamentselection_seed140_pop100_mut.01_snapshot_5000.csv")

random <- read_csv("../phylogeny_visualizations/nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv")


# Load reconstructions
sharing_reconstructed <- read_csv("phylogenetic-inference/a=reconstructed_phylogenies+source=nk_sharingselection_seed10_pop100_mut.01_snapshot_5000.csv")

ecoea_reconstructed <- read_csv("phylogenetic-inference/a=reconstructed_phylogenies+source=nk_ecoeaselection_seed110_pop100_mut.01_snapshot_3000.csv")

lexicase_reconstructed <- read_csv("phylogenetic-inference/a=reconstructed_phylogenies+source=nk_lexicaseselection_seed110_pop165_mut.01_snapshot_500.csv")

tournament_reconstructed <- read_csv("phylogenetic-inference/a=reconstructed_phylogenies+source=nk_tournamentselection_seed140_pop100_mut.01_snapshot_5000.csv")

random_reconstructed <- read_csv("phylogenetic-inference/a=reconstructed_phylogenies+source=nk_randomselection_seed7_pop100_mut.01_snapshot_5000.csv")



```



```{r}
to_newick(sharing, "sharing_ref.nwk")
to_newick(ecoea, "ecoea_ref.nwk")
to_newick(random, "random_ref.nwk")
to_newick(lexicase, "lexicase_ref.nwk")
to_newick(tournament, "tournament_ref.nwk")

sharing_trees <- sharing_reconstructed %>% 
                    group_by(Treatment) %>%
                    group_walk(~ to_newick(.x, paste0("sharing_reconstruction", .y$Treatment, ".nwk"))) %>%
                    summarize(filename = paste0("sharing_reconstruction", first(Treatment), ".nwk"))

ecoea_trees <- ecoea_reconstructed %>% 
                    group_by(Treatment) %>%
                    group_walk(~ to_newick(.x, paste0("ecoea_reconstruction", .y$Treatment, ".nwk"))) %>%
                    summarize(filename = paste0("ecoea_reconstruction", first(Treatment), ".nwk"))


random_trees <- random_reconstructed %>% 
                    group_by(Treatment) %>%
                    group_walk(~ to_newick(.x, paste0("random_reconstruction", .y$Treatment, ".nwk"))) %>%
                    summarize(filename = paste0("random_reconstruction", first(Treatment), ".nwk"))


lexicase_trees <- lexicase_reconstructed %>% 
                    group_by(Treatment) %>%
                    group_walk(~ to_newick(.x, paste0("lexicase_reconstruction", .y$Treatment, ".nwk"))) %>%
                    summarize(filename = paste0("lexicase_reconstruction", first(Treatment), ".nwk"))


tournament_trees <- tournament_reconstructed %>% 
                    group_by(Treatment) %>%
                    group_walk(~ to_newick(.x, paste0("tournament_reconstruction", .y$Treatment, ".nwk"))) %>%
                    summarize(filename = paste0("tournament_reconstruction", first(Treatment), ".nwk"))

```

```{r}

sharing_tree <- read.tree("sharing_ref.nwk")
sharing_recons = list()
for (row in sharing_trees$filename) {
  print(row)
  sharing_recons <- append(sharing_recons, list(read.tree(row)))
}
names(sharing_recons) <- sharing_trees$Treatment
testTrees <- append(sharing_recons, list(trueTree = sharing_tree))
sharing_info <- MutualClusteringInfo(testTrees$trueTree, testTrees)
sharing_info <- sharing_info / sharing_info['trueTree']
sharing_cid <- ClusteringInfoDistance(testTrees$trueTree, testTrees, normalize=TRUE)
sharing_rf <- NyeSimilarity(testTrees$trueTree, testTrees, normalize=TRUE)
```

```{r}

ecoea_tree <- read.tree("ecoea_ref.nwk")
ecoea_recons = list()
for (row in ecoea_trees$filename) {
  print(row)
  ecoea_recons <- append(ecoea_recons, list(read.tree(row)))
}
names(ecoea_recons) <- ecoea_trees$Treatment
testTrees <- append(ecoea_recons, list(trueTree = ecoea_tree))
ecoea_info <- MutualClusteringInfo(testTrees$trueTree, testTrees)
ecoea_info <- ecoea_info / ecoea_info['trueTree']
ecoea_cid <- ClusteringInfoDistance(testTrees$trueTree, testTrees, normalize=TRUE)
ecoea_rf <- NyeSimilarity(testTrees$trueTree, testTrees, normalize=TRUE)

```

```{r}

random_tree <- read.tree("random_ref.nwk")
random_recons = list()
for (row in random_trees$filename) {
  print(row)
  random_recons <- append(random_recons, list(read.tree(row)))
}
names(random_recons) <- random_trees$Treatment
testTrees <- append(random_recons, list(trueTree = random_tree))
random_info <- MutualClusteringInfo(testTrees$trueTree, testTrees)
random_info <- random_info / random_info['trueTree']
random_cid <- ClusteringInfoDistance(testTrees$trueTree, testTrees, normalize=TRUE)
random_rf <- NyeSimilarity(testTrees$trueTree, testTrees, normalize=TRUE)

```

```{r}

lexicase_tree <- read.tree("lexicase_ref.nwk")
lexicase_recons = list()
for (row in lexicase_trees$filename) {
  print(row)
  lexicase_recons <- append(lexicase_recons, list(read.tree(row)))
}
names(lexicase_recons) <- lexicase_trees$Treatment
testTrees <- append(lexicase_recons, list(trueTree = lexicase_tree))
lexicase_info <- MutualClusteringInfo(testTrees$trueTree, testTrees)
lexicase_info <- lexicase_info / lexicase_info['trueTree']
lexicase_cid <- ClusteringInfoDistance(testTrees$trueTree, testTrees, normalize=TRUE)
lexicase_rf <- NyeSimilarity(testTrees$trueTree, testTrees, normalize=TRUE)

```



```{r}

tournament_tree <- read.tree("tournament_ref.nwk")
tournament_recons = list()
for (row in tournament_trees$filename) {
  print(row)
  tournament_recons <- append(tournament_recons, list(read.tree(row)))
}
names(tournament_recons) <- tournament_trees$Treatment
testTrees <- append(tournament_recons, list(trueTree = tournament_tree))
tournament_info <- MutualClusteringInfo(testTrees$trueTree, testTrees)
tournament_info <- tournament_info / tournament_info['trueTree']
tournament_cid <- ClusteringInfoDistance(testTrees$trueTree, testTrees, normalize=TRUE)
tournament_rf <- NyeSimilarity(testTrees$trueTree, testTrees, normalize=TRUE)

```

```{r}
all_df <- data.frame(cbind(random_info, ecoea_info, sharing_info, tournament_info, lexicase_info, random_cid, ecoea_cid, sharing_cid, tournament_cid, lexicase_cid, random_rf, ecoea_rf, sharing_rf, tournament_rf, lexicase_rf)) %>%
              rownames_to_column(var = "Treatment") %>%
              mutate(target=str_extract(Treatment, "(?<=target=)[:digit:]*"),
                     differentia=as.numeric(str_extract(Treatment, "(?<=differentia=)[:digit:]*")),
                     policy=str_extract(Treatment, "(?<=policy=)[:alpha:]*")
                     ) %>% 
              pivot_longer(cols=contains("_"), names_to = "condition", values_to="score") %>%
              mutate(
                policy = case_when(
                  policy == "RecencyProportionalResolution" ~ "RPR",
                  policy == "TaperedDepthProportionalResolution" ~ "TDPR"
                  ),
                dist_fun = str_extract(condition,"(?<=_)[:alpha:]*"),
                condition = str_extract(condition,"[:alpha:]*(?=_)")
              ) 


all_df
```

```{r}
ggplot(all_df %>% filter(condition != "tournament", !is.na(policy))) + geom_bar(stat = "identity", aes(x=target, y=score, fill=policy, group=policy), position = position_dodge()) + facet_wrap(~condition*differentia) + theme(legend.position = "bottom") + theme_classic()

```

```{r}

ggplot(all_df %>% filter(dist_fun=="cid", condition == "sharing", !is.na(policy))) + geom_bar(stat = "identity", aes(x=target, y=score, fill=policy, group=policy), position = position_dodge()) + facet_wrap(~differentia,labeller = label_both) + theme(legend.position = "bottom") + theme_classic() + scale_x_discrete("Target bits", limits=c("64", "512", "4096")) + scale_y_continuous("Cluster information distance")
```

```{r}
oldPar <- par(mar = rep(0.1, 4))
TernaryPlot(alab = 'Absent information', blab = 'Shared information',
            clab = 'Misinformation',
            lab.cex = 0.8, lab.offset = 0.18,
            point = 'left', clockwise = FALSE,
            grid.col = '#dedede', grid.minor.lines = 0,
            axis.labels = 0:10 / 10, axis.col = "#aaaaaa")

HorizontalGrid()
correct <- MutualClusteringInfo(testTrees$trueTree, testTrees)
resolved <- ClusteringEntropy(testTrees)
unresolved <- resolved['trueTree'] - resolved
incorrect <- resolved - correct
results <- cbind(unresolved, correct, incorrect)
results[results < 0] <- 0

TernaryPoints(results, 
              pch = 1:3, cex = 2, col = Ternary::cbPalette8[1:3])
par(oldPar)
```

