#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATESTOCHASTIC_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATESTOCHASTIC_HPP_INCLUDE

namespace hstrat {

class StratumRetentionPredicateStochastic {
  // TODO
};

} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATESTOCHASTIC_HPP_INCLUDE
