#pragma once
#ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMAXIMAL_HPP_INCLUDE
#define HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMAXIMAL_HPP_INCLUDE

namespace hstrat {

class StratumRetentionPredicateMaximal {
  // TODO
};


} // namespace hstrat

#endif // #ifndef HSTRAT_STRATUM_RETENTION_PREDICATES_STRATUMRETENTIONPREDICATEMAXIMAL_HPP_INCLUDE
