name: CI
on:
  push:
    branches: [ master, dev, cut-cookie ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:

  docker-build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: "GITHUB_ACTION_${{ github.run_number }}"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/hereditary-stratigraph-concept
          registry: ghcr.io
          add_git_labels: true

  docker-teximage-build:
    name: Docker Tex Image Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Build and Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: true
          tags: "GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/hereditary-stratigraph-concept
          registry: ghcr.io
          path: ./tex/
          add_git_labels: true

  tidy:
    name: Tidy
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      - run: |
          cd /opt/hereditary-stratigraph-concept
          ./tidy/test_tidy.sh

  py-unit:
    name: Pylib Unit Tests
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --user root --cap-add=SYS_ADMIN
    steps:
      - run: /opt/hereditary-stratigraph-concept/pylib/test/run_tests.sh

  docs:
    name: Docs
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      - run: make html -C /opt/hereditary-stratigraph-concept/docs

  binder:
    name: Notebooks
    runs-on: ubuntu-20.04
    needs:
      - docker-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      # Adapted from https://askubuntu.com/a/524368
      - run: cd /opt/hereditary-stratigraph-concept/binder && ./execute_notebooks.sh
      - run: git init
      - run: git config --global --add safe.directory '*'
      - uses: fregante/setup-git-user@v1
      - run: git commit --allow-empty -m "Initial commit"
      - run: cp -r /opt/hereditary-stratigraph-concept/ deploy/
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: binder # The branch the action should deploy to.
          folder: deploy # The folder the action should deploy.

  latex:
    name: Latex Build
    runs-on: ubuntu-20.04
    needs:
      - docker-teximage-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make -C tex
      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: manuscript
          path: tex/hereditary-stratigraph-concept-draft.pdf

  latex-extended-abstract:
    name: Latex Extended Abstract Build
    runs-on: ubuntu-20.04
    needs:
      - docker-teximage-build
    container:
      image: ghcr.io/mmore500/hereditary-stratigraph-concept:GITHUB_ACTION_${{ github.run_number }}_TEXIMAGE
      # github actions requires root to access mounted volumes
      options: --user root
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run: make -C tex-extended-abstract
      - name: Upload output as artifact
        uses: actions/upload-artifact@v2
        with:
          name: manuscript-abstract
          path: tex-extended-abstract/hereditary-stratigraph-concept-draft.pdf


  deploy-container:
    name: Deploy Container to ghcr.io
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/cut-cookie'
    needs:
      - binder
      - docs
      - latex
      - latex-extended-abstract
      - py-unit
      - tidy
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0 # fetch all history for all branches and tags
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: mmore500/hereditary-stratigraph-concept
          registry: ghcr.io
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
